### PR TITLE
Remove unused class which is not part of upstream library

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by bhoppi** [comment]
The code was forked from org.apache.spark.util.collection.PrimitiveVector originally, but now it is not needed any more. I forgot to remove it.
Thank you.

**Comment by benmccann** [comment]
Do you want to merge this PR then?

**Comment by bhoppi** [comment]
Yes, but I don't have permission. @witgo @hucheng

**Comment by witgo** [comment]
Thanks, merged.

**Pull request merged**
